# Uncomment the next line to define a global platform for your project

source 'https://git.coding.net/MasonHe/GeneralRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'xd_proprietor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xd_proprietor
#  pod 'SYStickHeaderWaterFall'
  pod 'UICollectionViewLeftAlignedLayout', '~> 1.0.2'
  pod 'YYKit'
  pod 'SDCycleScrollView'
  pod 'HMSegmentedControl'
  pod 'PageContainer'
  pod 'HCSStarRatingView', '~> 1.4.5'
  pod 'MJRefresh'
  pod 'MJExtension'
#  pod 'MBProgressHUDExtension'

end
